apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
  labels:
    app: go-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: web
          image: rhachsec/lesson1:v0.2
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/data"
            name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-pvc