apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"goweb"},"name":"static-web","namespace":"lesson14"},"spec":{"containers":[{"image":"lesson1:v0.2","name":"web","ports":[{"containerPort":8080,"name":"web","protocol":"TCP"}],"resources":{"limits":{"cpu":"1","memory":"512Mi"},"requests":{"cpu":"0.2","memory":"256Mi"}}}]}}
  creationTimestamp: "2021-08-16T09:00:27Z"
  labels:
    app: goweb
  name: static-web
  namespace: lesson14
  resourceVersion: "4407"
  uid: 0f4ae981-bef8-46de-8b03-26d87fb655a7
spec:
  containers:
  - image: rhacksec/lesson1:v0.2
    imagePullPolicy: IfNotPresent
    name: web
    ports:
    - containerPort: 8080
      name: web
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zqsgz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-zqsgz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-16T09:00:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-16T09:00:27Z"
    message: 'containers with unready status: [web]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-16T09:00:27Z"
    message: 'containers with unready status: [web]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-16T09:00:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: lesson1:v0.2
    imageID: ""
    lastState: {}
    name: web
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "lesson1:v0.2"
        reason: ImagePullBackOff
  hostIP: 192.168.49.2
  phase: Pending
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: Burstable
  startTime: "2021-08-16T09:00:27Z"
